Feat/CatBoost model
unit8co/darts pull request #1007
Opened 2022-06-13 21:45 UTC by jonasracine

- Added Catboost regression model. Currently, supports same probabilistic prediction possibilities (quantile and poisson) as Dart's LGBM implementation.

- The Catboost class is mostly a copy-paste of the LGBM class. 
**Question**: should this be refactored to avoid code duplication?

- Future work: add support for Catboost's own "RMSEWithUncertainty" loss function, that returns [mean, variance] (see https://towardsdatascience.com/tutorial-uncertainty-estimation-with-catboost-255805ff217e)

2022-06-15 12:55 UTC, hrzn requested changes
Thanks @jonasracine , it looks like a good start.
Could you add unit tests?
Concerning factoring out the code, I think it's not necessary at the moment (we can do it later if we have more similar models coming).
Finally, how much work is it to add the RMSE mu/sigma version? It's probably not too difficult I imagine, in which case I'd vote for making it part of this PR.

2022-06-16 14:59 UTC, jonasracine commented on darts/models/forecasting/catboost_model.py
> +if __name__ == "__main__":
Done!

2022-06-21 18:29 UTC, hrzn commented
@jonasracine there are ~60 `.coverage` files committed too :) could you remove them?

2022-06-27 05:31 UTC, hrzn approved these changes
LGTM, thanks

2022-06-27 10:54 UTC, merged