Convert hierarchy parents to list if string
unit8co/darts pull request #1584
Opened 2023-02-21 08:53 UTC by DavidKleindienst

Fixes #1581.

### Summary

This PR allows TimeSeries to accept hierarchy of the format `{child_component: parent_component}`, removing the need to specify parent components as list if there is only one parent

### Other Information

The check for string is implemented as `isinstance(parent, string) and parent in ts.components` for backwards compatibility:
Currently, it is possible to use single letters as component names (e.g. "a", "b", "c") and specify `{"a": "bc"}  to mean "a" is a child of  "b" and "c". This behavior is kept unless "bc" is also a component. 
Let me know if this makes sense, or it's better to remove this check and interpret "bc" always as ["bc"] even if no "bc" component exists.

2023-03-19 12:02 UTC, dennisbader requested changes
Thank you @DavidKleindienst for this PR, and sorry for the long wait!

Looks good already, just had some minor suggestions to avoid mutating the user's hierarchy object:)

2023-03-20 10:15 UTC, DavidKleindienst commented
Thanks for reviewing @dennisbader 
I've added the changes you suggested

2023-03-20 19:16 UTC, dennisbader approved these changes

2023-03-20 19:17 UTC, dennisbader commented
Thanks! Ready to merge 🚀

2023-03-20 19:17 UTC, merged