Fix/1457 add support for static covariates to shap
unit8co/darts pull request #1732
Opened 2023-04-26 11:22 UTC by anne-devries

Before you couldn't use ShapExplainer when your regression model used static covariates. This PR fixes this issue.

### Summary

### Other Information

2023-04-26 11:30 UTC, anne-devries commented
@dennisbader I created the pull request for this change. Not sure if I missed something, if so just let me know! Also:

The PR I now created contains this unittest: test_shapley_multiple_series_with_different_static_covs. In tabularization.py, if the model uses static_covariates, only the static covariates of one target series are used. Shouldn't there be a validation check to see if different target series have different static covariates?

2023-05-01 13:09 UTC, madtoinou reviewed
Hi @anne-devries,

Thank you for contributing to darts! Looks good, a few minors comments about optimization.

Also, it seems like there are some linting issues : can you please follow the [instructions](https://github.com/unit8co/darts/blob/master/CONTRIBUTING.md#code-formatting-and-linting) to apply it automatically?

Thank you for adding tests!

2023-05-01 13:09 UTC, madtoinou commented on darts/explainability/shap_explainer.py
> +            X[i] = X_i[:, :, 0]
I would rather keep the first implementation, without the loop.

2023-05-01 13:09 UTC, madtoinou commented on darts/explainability/shap_explainer.py
> +        X = np.concatenate(X, axis=0)
This should not be necessary if the operation are performed on the array directly (instead of the for loop)

2023-05-02 08:39 UTC, madtoinou commented on darts/explainability/shap_explainer.py
> +            X[i] = X_i[:, :, 0]
You're indeed correct, I overlooked the multi-timeseries scenario.

It's alright like this!

2023-05-06 13:26 UTC, dennisbader commented
Thanks for this @anne-devries, this was long on our TODO list 🚀  let me review it next week.

2023-05-16 14:26 UTC, dennisbader requested changes
Hi @anne-devries and thanks for this great PR. 🚀 

Just had some minor suggestions after which it'll be ready to get merged!

2023-05-16 14:26 UTC, dennisbader commented on darts/tests/explainability/test_shap_explainer.py
> +        # test black
```suggestion
        # model trained on multiple series will take column names of first series -> even though
        # static covs have different names, the output will show the same names
        for explained_forecast in explanation_results.explained_forecasts:
            comps_out = explained_forecast[1]["price"].columns.tolist()
            assert comps_out[-1] == "type_statcov_target_price"
```

2023-05-28 13:59 UTC, dennisbader commented
Hi @anne-devries, thanks for your work! I will close this one as I had to implement the changes in the meantime for PR #1803. I added your contribution to the CHANGELOG of that PR.

2023-05-28 13:59 UTC, closed without merging

2023-05-28 14:29 UTC, vsantosu commented
Thanks so much!! Great work btw! this is a very powerful project.

2023-05-30 06:49 UTC, anne-devries commented
@dennisbader thanks! Sorry that I didn't fix those suggestions you had earlier on. Create that this functionality is now merged though! :)