Fix broken link in 00-quickstart.ipynb
unit8co/darts pull request #1793
Opened 2023-05-22 03:22 UTC by EngineerDanny

Fixes #1792 .

### Summary

This pull request fixes the broken documentation link for the LightGBMModel class. It replaces the old link with the correct one.

### Other Information

This is a minor change that does not affect the functionality of the library.

2023-05-23 07:46 UTC, dennisbader requested changes
Thanks @EngineerDanny for this.
I left a comment about not rerunning the entire notebook but only saving with the changed text.

2023-05-23 07:46 UTC, dennisbader commented on examples/00-quickstart.ipynb
Instead of rerunning the entire notebook and then saving, could you just update the relevant text for the LGBM link and save the notebook?
Otherwise this creates a huge diff as you can see on the top left.

2023-05-25 15:05 UTC, EngineerDanny commented
I have updated the branch. It's now in sync with the master. All checks should pass successfully now.

2023-05-26 11:52 UTC, dennisbader approved these changes
Perfect, thanks for the changes and the fix @EngineerDanny 💯  🚀

2023-05-26 11:52 UTC, merged