added cumsum function to time series
unit8co/darts pull request #1988
Opened 2023-09-09 01:25 UTC by Eliotdoesprogramming

Fixes #1981 

### Summary
adds the cumsum function to the Timeseries class. Implementation uses the xarray implementation of cumsum. 

Additionally adds unit tests for the cumsum function when n=1 and n=2

let me know if this needs any more refinement, thanks!

2023-09-13 09:10 UTC, dennisbader requested changes
Thanks a lot for this PR @Eliotdoesprogramming 🚀 

I added some suggestions, mainly that I would opt for dropping support for `n` in cumsum.

After that we can merge :)

2023-09-13 09:10 UTC, dennisbader commented on darts/tests/test_timeseries.py
> +            self.series1.diff(n=0.2)
This tests diff rather then cumsum. From my comment below I would opt for dropping `n` support

2023-09-13 09:10 UTC, dennisbader commented on darts/tests/test_timeseries.py
> +            self.series1.diff(n=0.2)
```suggestion
        cumsum = TimeSeries.from_dataframe(self.series1.pd_dataframe().cumsum())
        assert self.series1.cumsum() == cumsum
```

2023-09-14 10:18 UTC, dennisbader approved these changes
Thanks @Eliotdoesprogramming for this PR, looks great now 🚀 

I applied the requested changes as we want to release the new version soon.

2023-09-14 10:18 UTC, merged

2023-09-15 16:46 UTC, Eliotdoesprogramming commented
np thanks for doing it! I get a bit busy during the week. Happy to contribute