fix: update hierarchy for single transform window_transform
unit8co/darts pull request #2207
Opened 2024-02-05 08:46 UTC by madtoinou

Fixes #2204.

### Summary

- If `window_transform()` is called with only one transform on all the components of the series, update the hierarchy with the new components names, otherwise, it's dropped.

2024-02-05 13:25 UTC, dennisbader requested changes
Thanks for giving this a go @madtoinou 🚀 
It seems like the issue has not yet been fully fixed with these changed (i tried running the code snippet from the issue).

I left some comments/suggestions

2024-02-05 13:25 UTC, dennisbader commented on darts/timeseries.py
> +                and transforms[0]["components"] != self.components
It will raise an error, since we're comparing a list with a pandas Index.
Also this comparison is not order-agnostic. Can we improve it?

2024-02-05 13:25 UTC, dennisbader commented on darts/timeseries.py
I noticed that when performing a single transform on all components, the hierarchy is also not preserved because the component names change.
Should we try to keep the hierarchy? Also for multiple transforms, we could keep the hierarchy across different transforms. What do you think?

2024-02-05 13:25 UTC, dennisbader commented on darts/timeseries.py
> +            if comp_names_map:
at this point, `comp_names_map` will always be `None` or an empty dict

2024-02-05 18:54 UTC, madtoinou commented on darts/timeseries.py
Yeah, this is the reason for the error mentioned in the issue.
For me, the hierarchy can be kept only if the transform is applied to all the components (otherwise, the relationship between the components might be lost).
If there are multiple transforms, the hierarchy can be kept (kind of duplicated) but it'll become quite difficult to read. Not sure how useful it will be but I will adapt the code so that it's supported.

2024-02-16 14:28 UTC, dennisbader reviewed
Thanks @madtoinou :) some last few suggestions, then it's ready.

2024-02-16 14:28 UTC, dennisbader commented on darts/timeseries.py
> +                comp_names_map = dict()
Let's define this dict for all cases (outside the if/else scope). Then we avoid the "this variable might be undefined" warnings further down

2024-02-16 14:28 UTC, dennisbader commented on darts/timeseries.py
> +                            comp_name: f"{name_prefix}_{comp_name}"
Let's do zip() and use the new names from the list above

2024-02-16 14:28 UTC, dennisbader commented on darts/tests/dataprocessing/transformers/test_window_transformations.py
> +            )
Shall we check that it raises the correct error (message)?

2024-02-16 14:28 UTC, dennisbader commented on darts/timeseries.py
Can we add the new arguments to the WindowTransformer as well?

2024-02-18 19:57 UTC, VascoSch92 commented on darts/timeseries.py
> +        several_transforms = len(transforms) > 1
you are defining this variable here but you are using it after 40 lines. 
I will put the variable definition above the line where you use it, or I will not use this variable at all.

2024-02-24 12:37 UTC, merged