Add optional inverse transform in historical forecast
unit8co/darts pull request #2267
Opened 2024-03-05 08:33 UTC by alicjakrzeminska

Implements #2260.

### Summary

This PR implements the possibility to inverse transform the output of the `historical_forecasts`. It is activated by passing `scaler` to `historical_forecasts`.

### Other Information

I see two places where this functionality can be implemented:`Scaler` class or `historical_forecasts`. The `Scaler` class is very generic so I didn't want to put such a detail there and decided to add this feature as an option in `historical_forecasts`.

2024-03-05 08:56 UTC, VascoSch92 commented on darts/models/forecasting/forecasting_model.py
> +        if not forecasts_list_transformed:
i don't get this point. If `forecasts_list_transformed` is empty you are doing nothing right?

Can you check that before calling the method? 

The method is private, so it should be used within this class.

Make it sense? :-)

2024-03-05 08:56 UTC, VascoSch92 commented on darts/models/forecasting/forecasting_model.py
> +            forecasts_list_inversely_transformed = scaler.inverse_transform(
```suggestion
            return scaler.inverse_transform(
```
in this way you don't have to go down in the method to check what is returned in this case :-)

2024-03-05 08:56 UTC, VascoSch92 commented on darts/models/forecasting/forecasting_model.py
> +            forecasts_list_inversely_transformed = list(
at this stage here the list is not inversely transformed. Perhaps another name for this variable.

2024-03-05 08:56 UTC, VascoSch92 commented on darts/models/forecasting/forecasting_model.py
> +        Uses the scaler trained previously on the same set of series.
```suggestion
        """Applies inverse transform on the list (of lists) of forecasts,
        using the scaler trained previously on the same set of series.
```

2024-03-05 08:56 UTC, VascoSch92 commented on darts/models/forecasting/forecasting_model.py
> +            Optionally, the scaler trained on the same `series`, performs inverse transform on the generated forecasts.
```suggestion
        scaler
            Optionally, the scaler trained on the same `series` is used to perform an inverse transform on the generated forecasts.
```

2024-03-05 13:57 UTC, dennisbader requested changes
Thanks for this Draft PR @alicjakrzeminska. I would suggest to move the logic to `darts.dataprocessing.transformers.invertible_data_transformer.InvertibleDataTrasnformer`. In my opinion this can generally be applied to any `InvertibleDataTransfomer`. What do you think?

2024-03-08 13:00 UTC, VascoSch92 commented on darts/dataprocessing/transformers/invertible_data_transformer.py
> +        * [[A1, A2, A3], [B1, B2], [C1, C2, C3]] - list of lists of series,
```suggestion
        -  [A1, B1, C1] - list of series,
        -  [[A1, A2, A3], [B1, B2], [C1, C2, C3]] - list of lists of series,
```

2024-03-08 13:00 UTC, VascoSch92 commented on darts/dataprocessing/transformers/invertible_data_transformer.py
> +        Allows for missing series the list.
```suggestion
        Supports lists of varying lengths and missing elements within the list/s.
```

2024-03-08 14:04 UTC, alicjakrzeminska commented
@dennisbader, I moved the function to `InvertibleDataTransfomer `. Please, take a look, and if you find it ok, I'll add some tests.
@VascoSch92, thank you for your feedback, I applied your suggestions. :)

2024-03-14 16:02 UTC, alicjakrzeminska commented
@dennisbader, I integrated the functionality with `inverse_transform` method of `InvertibleDataTransfomer ` as you suggested. Please, have a look, and I'll write the docstrings and tests if it's ok for you.

2024-03-16 07:55 UTC, VascoSch92 commented on darts/dataprocessing/transformers/invertible_data_transformer.py
> +                    data.append(series_)
```suggestion
                input_series.extend(series_list)
                data.extend(series_list
```

2024-03-16 10:15 UTC, dennisbader approved these changes
Really nice, thanks a lot for this great PR @alicjakrzeminska 🚀

2024-03-16 11:05 UTC, merged