add `DataLoader` related parameters to `fit()` and `predict()`
unit8co/darts pull request #2295
Opened 2024-03-27 17:16 UTC by BohdanBilonoh

Checklist before merging this PR:
- [x] Mentioned all issues that this PR fixes or addresses.
- [x] Summarized the updates of this PR under **Summary**.
- [x] Added an entry under **Unreleased** in the [Changelog](../CHANGELOG.md). 

### Summary

Add `torch.utils.data.DataLoader` related parameters to `fit()` and `predict()` of `TorchForecastingModel`

2024-05-06 15:24 UTC, madtoinou commented
Hi @BohdanBilonoh,

It looks great, however to make it easier to maintain and more exhaustive, I think that it would be great to just add an argument called `dataloader_kwargs`, then check that the argument explicitly used by Darts are not redundant/overwritten and then pass this argument down to the `DataLoader` constructor.

It will allow users to specify more than just `prefetch_factor`, `persistent_workers` and `pin_memory`, while limiting copy-pasting from other library documentation (putting a link to the `torch.DataLoader` page does sound like a good idea for this argument however)

2024-05-07 01:57 UTC, joshua-xia commented
Hi @BohdanBilonoh, Would you please add multiprocessing_context parameter for Dataloader, it is useful when we use multi-workers for dataloader, Thanks!

2024-05-07 01:59 UTC, joshua-xia commented
> Hi @BohdanBilonoh, Would you please add multiprocessing_context parameter for Dataloader, it is useful when we use multi-workers for dataloader, Thanks!

@BohdanBilonoh refer to #2375

2024-05-07 02:05 UTC, joshua-xia commented
> > Hi @BohdanBilonoh, Would you please add multiprocessing_context parameter for Dataloader, it is useful when we use multi-workers for dataloader, Thanks!
> 
> @BohdanBilonoh refer to #2375

@BohdanBilonoh  My bad, it is good idea from @madtoinou to add dataloader_kwargs to let user input dataloader parameters as wish freely, not need to support multiprocessing_context parameter forcibly

2024-05-28 09:46 UTC, BohdanBilonoh commented
@madtoinou what do you think about hardcoded parameters like

```python
batch_size=self.batch_size,
shuffle=True,
drop_last=False,
collate_fn=self._batch_collate_fn,
```

should it be hard coded for new `dataloader_kwargs` like

```python
def _setup_for_train(
    self,
    train_dataset: TrainingDataset,
    val_dataset: Optional[TrainingDataset] = None,
    trainer: Optional[pl.Trainer] = None,
    verbose: Optional[bool] = None,
    epochs: int = 0,
    dataloader_kwargs: Optional[Dict[str, Any]] = None,
) -> Tuple[pl.Trainer, PLForecastingModule, DataLoader, Optional[DataLoader]]:

        ...

        if dataloader_kwargs is None:
            dataloader_kwargs = {}

        dataloader_kwargs["shuffle"] = True
        dataloader_kwargs["batch_size"] = self.batch_size
        dataloader_kwargs["drop_last"] = False
        dataloader_kwargs["collate_fn"] = self._batch_collate_fn

        # Setting drop_last to False makes the model see each sample at least once, and guarantee the presence of at
        # least one batch no matter the chosen batch size
        train_loader = DataLoader(
            train_dataset,
            **dataloader_kwargs,
        )

        dataloader_kwargs["shuffle"] = False

        # Prepare validation data
        val_loader = (
            None
            if val_dataset is None
            else DataLoader(
                val_dataset,
                **dataloader_kwargs,
            )
        )
```

or give a user full control on `dataloader_kwargs`?

2024-05-30 17:47 UTC, tRosenflanz commented
> @madtoinou what do you think about hardcoded parameters like
> 
> ```python
> batch_size=self.batch_size,
> shuffle=True,
> drop_last=False,
> collate_fn=self._batch_collate_fn,
> ```
> 
> should it be hard coded for new `dataloader_kwargs` like
> 
> ```python
> def _setup_for_train(
>     self,
>     train_dataset: TrainingDataset,
>     val_dataset: Optional[TrainingDataset] = None,
>     trainer: Optional[pl.Trainer] = None,
>     verbose: Optional[bool] = None,
>     epochs: int = 0,
>     dataloader_kwargs: Optional[Dict[str, Any]] = None,
> ) -> Tuple[pl.Trainer, PLForecastingModule, DataLoader, Optional[DataLoader]]:
> 
>         ...
> 
>         if dataloader_kwargs is None:
>             dataloader_kwargs = {}
> 
>         dataloader_kwargs["shuffle"] = True
>         dataloader_kwargs["batch_size"] = self.batch_size
>         dataloader_kwargs["drop_last"] = False
>         dataloader_kwargs["collate_fn"] = self._batch_collate_fn
> 
>         # Setting drop_last to False makes the model see each sample at least once, and guarantee the presence of at
>         # least one batch no matter the chosen batch size
>         train_loader = DataLoader(
>             train_dataset,
>             **dataloader_kwargs,
>         )
> 
>         dataloader_kwargs["shuffle"] = False
> 
>         # Prepare validation data
>         val_loader = (
>             None
>             if val_dataset is None
>             else DataLoader(
>                 val_dataset,
>                 **dataloader_kwargs,
>             )
>         )
> 
>         ...
> ```
> 
> or give a user full control on `dataloader_kwargs`?

you could extend your suggestion to allow overrides but with populated defaults 
```
defaults = dict(shuffle = True, batch_size = self.batch_size, drop_last = False, collate_fn = self._batch_collate_fn)
#combine with defaults but override them
dataloader_kwargs_train = {**defaults,**dataloader_kwargs}
#override shuffle
dataloader_kwargs_val = (**dataloader_kwargs_train, **dict(shuffle=False)} 
```

2024-05-31 15:20 UTC, dennisbader requested changes
Thanks for the updates @BohdanBilonoh, I took the chance to fix some indentation issues in one of the docstrings and pushed the changes.

If we give the freedom to overwrite our default dataloader params when calling `fit()`, shouldn't we then also allow that during `predict()`?

Also, removing the `num_loader_workers` parameter is a breaking change. Can you document this in the CHANGELOG.md?

2024-05-31 15:20 UTC, dennisbader commented on darts/models/forecasting/torch_forecasting_model.py
> +        if data_loader_kwargs is None:
Shouldn't we allow then here as well the liberty to overwrite these defaults (expect shuffle)?

2024-05-31 15:22 UTC, dennisbader commented on darts/models/forecasting/torch_forecasting_model.py
> +            Optionally, a dictionary of keyword arguments to pass to the PyTorch DataLoader instances used to load the
it's referring to the train and val datasets, but it should be for the prediction dataset, same for the methods below

2024-06-03 09:15 UTC, dennisbader approved these changes
Thanks for the changes @BohdanBilonoh. I made some last updates including unit tests and some docstrings.

Looks great now, and ready to be merged once tests have passed!

Thanks a lot for the great work 🚀

2024-06-03 09:18 UTC, madtoinou approved these changes

2024-06-03 11:25 UTC, merged