Update README.md to be more colorblind friendly
unit8co/darts pull request #2433
Opened 2024-06-28 17:11 UTC by jatins

Checklist before merging this PR:
- [ ] Mentioned all issues that this PR fixes or addresses.
- [ ] Summarized the updates of this PR under **Summary**.
- [ ] Added an entry under **Unreleased** in the [Changelog](../CHANGELOG.md).

Fixes #.

### Summary
I had trouble differentiation green/red squares in readme, this make it a little more colorblind friendly. I just find/replaced the emojis so the rest of text should be unchanged

### Other Information

2024-07-01 07:47 UTC, dennisbader requested changes
Thanks for this PR @jatins, I think that makes sense :)
Could you add an entry to the changelog? Then we're ready to merge 🚀

2024-07-01 07:47 UTC, dennisbader commented on README.md
> +
```suggestion
```

2024-07-05 10:06 UTC, jatins commented
@dennisbader thanks for having a look! Changes:
* Updated the changelog 
* removed redundant whitespace

2024-07-05 12:20 UTC, dennisbader approved these changes
Thanks a lot @jatins, ready to merge 🚀

2024-07-05 12:21 UTC, merged