Update ruff to v6.8
unit8co/darts pull request #2548
Opened 2024-09-29 04:37 UTC by gdevos010

Checklist before merging this PR:
- [ ] Mentioned all issues that this PR fixes or addresses.
- [ ] Summarized the updates of this PR under **Summary**.
- [ ] Added an entry under **Unreleased** in the [Changelog](../CHANGELOG.md).

Fixes #.

### Summary

### Other Information

2024-09-29 07:07 UTC, madtoinou requested changes
Thanks @gdevos010 for this PR, looks good overall.

Can you please revert the changes to the images in the notebooks? Also, found some changes in the code that might cause some issues.

Also, we need to make sur follow the migrations instruction from 0.3.6 to 0.6.8 to avoid issues.

2024-09-29 07:07 UTC, madtoinou commented on examples/02-data-processing.ipynb
Please revert the changes to the images

2024-09-29 07:07 UTC, madtoinou commented on examples/03-FFT-examples.ipynb
Please revert the changes to the images

2024-09-29 07:07 UTC, madtoinou commented on examples/11-GP-filter-examples.ipynb
Revert changes to images

2024-09-29 07:07 UTC, madtoinou commented on pyproject.toml
Why did you remove that?

2024-09-29 16:59 UTC, gdevos010 commented on pyproject.toml
It's deprecated in v6.8

2024-11-08 11:15 UTC, madtoinou commented
Replaced by #2589.

2024-11-08 11:15 UTC, closed without merging