Feat/onnx support
unit8co/darts pull request #2620
Opened 2024-12-17 00:49 UTC by madtoinou

Checklist before merging this PR:
- [ ] Mentioned all issues that this PR fixes or addresses.
- [ ] Summarized the updates of this PR under **Summary**.
- [ ] Added an entry under **Unreleased** in the [Changelog](../CHANGELOG.md).

Fixes  #553,  #2617

### Summary

- Small refactoring of the `_process_input_batch` and `_get_batch_prediction()` methods to make the behavior uniform across PLModules
- Added `to_onnx` method to the `TorchForecastingModel` class, taking care of creating the `input_names` and `input_sample` based on the model attributes
- Added a section in the User Guide to show how to export and load the model to generate forecasts

### Other Information

The consistency of the forecasts was tested in a notebook for all the possible configurations, I did not implement unit-test as onnx should remain an optional dependency. Let me know what you think.

2025-01-24 16:01 UTC, dennisbader requested changes
Very cool feature, thanks a lot @madtoinou 🚀 Looks like we're close already to merge :)

I had a couple of suggestions regarding the example and the export logic, where I see potential to simplify things further.

2025-01-25 18:06 UTC, madtoinou commented on docs/userguide/torch_forecasting_models.md
> +#### Exporting model to ONNX format for inference
Yeah, definitely, it would make a lot of things more intuitive and easier to tweak for users.

2025-01-25 18:44 UTC, madtoinou commented on darts/models/forecasting/torch_forecasting_model.py
> +        if not self._fit_called:
Yeah, it should be. I simplified all the logic.

2025-02-19 10:31 UTC, madtoinou commented on docs/userguide/torch_forecasting_models.md
> +#### Exporting model to ONNX format for inference
Created #2686

2025-02-19 13:38 UTC, dennisbader approved these changes
Looks great now, thanks a lot for changes 🚀  Love this PR 😍

2025-02-19 16:04 UTC, merged