Fix/val_sample_weight error for models inherited from RegressionModel
unit8co/darts pull request #2626
Opened 2024-12-21 03:05 UTC by KylinSchmidt

Checklist before merging this PR:
- [x] Mentioned all issues that this PR fixes or addresses.
- [x] Summarized the updates of this PR under **Summary**.
- [x] Added an entry under **Unreleased** in the [Changelog](../CHANGELOG.md).

Fix the bug in [#2579 ](https://github.com/unit8co/darts/issues/2579)  that causes an error when `val_sample_weight` is set in the CatBoost and XGBoost models.

### Summary

The CatBoost and XGBoost models, which inherit from the RegressionModel class, encounter an error when setting val_sample_weight. This issue is resolved by modifying the _add_val_set_to_kwargs method in RegressionModel, changing val_weights = val_weight to val_weights = [val_weight].

### Other Information

2024-12-30 09:13 UTC, madtoinou requested changes
Looks good, thank you for your contribution.

Can you please add unit-tests so that we can make sure the fix works as expected for all the situations?

2024-12-30 09:13 UTC, madtoinou commented on CHANGELOG.md
> +- Fix the bug in [#2579 ](https://github.com/unit8co/darts/issues/2579)  that causes an error when `val_sample_weight` is set in the CatBoost and XGBoost models.
```suggestion
- Fix a bug in `RegressionModel` when `val_sample_weight` is used with a single timeseries. [#2626](https://github.com/unit8co/darts/pull/2626) by [Kylin Schmidt](https://github.com/kylinschmidt).
```

2024-12-30 09:13 UTC, madtoinou commented on CHANGELOG.md
> +
Can you revert this change and the others below?

2024-12-30 09:13 UTC, madtoinou commented on darts/models/forecasting/regression_model.py
> +            val_weights = [val_weight]
Looks neat!

2025-02-14 15:22 UTC, dennisbader approved these changes
Thanks @KylinSchmidt for this fix 🚀 I took the liberty to push some changes (unit tests, and the suggestions from @madtoinou ).

Everything looks great now, ready to merge 💯

2025-02-14 16:04 UTC, merged