Added .to(self.device) to covariate data as well in predict function
unit8co/darts pull request #425
Opened 2021-08-06 09:36 UTC by spazzy

Fixes #413.

### Summary

The _predict_batch_recurrent_model function uses torch.cat, which requires the concatenated data to be on the same device. The data of the input series was already moved to the selected device, but the covariate data wasn't. This patch moves the covariate data to the selected device as well.

2021-08-06 10:30 UTC, pennfranc approved these changes
Looks good to me, thanks!

2021-08-06 11:28 UTC, hrzn requested changes
Thanks for this! However this problem has already been fixed in the develop branch (all PRs should target develop, not master).

2021-08-06 13:53 UTC, spazzy commented
Ah great. Didn't know that. I will close this PR then.

2021-08-06 13:53 UTC, closed without merging

2021-08-08 07:34 UTC, pennfranc commented
@hrzn Ah sorry didn't notice the base branch was master!