fix end_ts+1
unit8co/darts pull request #555
Opened 2021-11-19 14:18 UTC by dumjax

Fix to respect the definition of the method slice of TimeSeries. 

### Summary

TimeSeries slice method explicitly states:
Returns a new TimeSeries, starting later than `start_ts` and ending before `end_ts`, inclusive on both ends.
Nevertheless, in the case start_ts and end_ts are int, the range of index was defined by pd.RangeIndex(start_ts, end_ts, step=1) which means that end side was excluded. We just have to replace by end_ts+1.

### Other Information

2021-11-19 14:24 UTC, hrzn commented
Could we maybe add a test case to capture this case in the future? That might turn out useful :D

2021-11-20 11:03 UTC, tomasvanpottelbergh commented
Should the slicing method actually include the end? In my experience, you often want to exclude the end (slicing from midnight till midnight to cover a full day for example). Or do you think the current definition is more useful?

2021-11-22 12:38 UTC, dumjax commented
> 

I had the same question cause intuitively I would have said that we need to follow python way (excluding last element). But it was defined since the beginning like this and maybe there are some other parts which depends on this.

2021-11-22 16:55 UTC, hrzn commented
I have made some tests and it's OK to make the interval open on the right. I just had to adapt a couple of unit tests, but nothing major was relying on it (in fact `slice()` should probably be deprecated - we prefer slicing with `[]` instead). I've updated the PR.

2021-11-22 16:55 UTC, hrzn approved these changes

2021-11-23 08:03 UTC, tomasvanpottelbergh requested changes

2021-11-23 08:03 UTC, tomasvanpottelbergh commented on darts/timeseries.py
> +            idx = pd.RangeIndex(start_ts, end_ts+1, step=1)
Shouldn't this change be reverted and a test added?

2021-11-24 16:20 UTC, hrzn commented
As discussed recently with @dumjax - we'll close it. Having exclusive bounds on ints and inclusive on datetimes matches the Pandas way to index (and our `[]` operator too), so we'll leave it as is for now. We could revisit it at some point, because actually when ints represent time steps (and not indexes), one could make the case that all bounds should be inclusive.

2021-11-24 16:20 UTC, closed without merging