allow for ETS with seasonal=None
unit8co/darts pull request #729
Opened 2022-01-09 20:02 UTC by john-ramsey

Fixes: Allow fitting an exponential smoothing model with `seasonal = None`. Ex: Annual Data

### Summary

Currently when trying to fit an ETS model with `seasonal = None` the following error is returned:
`AttributeError: 'NoneType' object has no attribute 'value'`

Example:
```
df = pd.DataFrame(index = pd.date_range(start='1/1/2020', periods=10, freq='A'), data = [i+1 for i in range(10)])
ts = TimeSeries.from_dataframe(df)
mdl = ExponentialSmoothing(seasonal=None)
mdl.fit(ts)
```

### Proposed Fix
Add an if statement which allows for the passing of None into the seasonal component.

2022-01-09 20:42 UTC, dennisbader commented
Hi @john-ramsey and thanks a lot for the PR.

Actually, you can already create a model without seasonality with `ExponentialSmoothing(seasonal=SeasonalityMode.NONE)` or `seasonal=ModelMode.NONE` (see [this answer](https://github.com/unit8co/darts/issues/552#issuecomment-970205490))

The model documention however is a bit misleading especially 

https://github.com/unit8co/darts/blob/4a97140391f171e151c10ac6889eb9a9ce1ba70f/darts/models/forecasting/exponential_smoothing.py#L35

and 

https://github.com/unit8co/darts/blob/4a97140391f171e151c10ac6889eb9a9ce1ba70f/darts/models/forecasting/exponential_smoothing.py#L49-L51

If you want, you could adapt these lines instead for the PR? :)

2022-01-09 20:43 UTC, dennisbader requested changes
Hi @john-ramsey and thanks a lot for the PR.

Actually, you can already create a model without seasonality with `ExponentialSmoothing(seasonal=SeasonalityMode.NONE)` or `seasonal=ModelMode.NONE` (see [this answer](https://github.com/unit8co/darts/issues/552#issuecomment-970205490))

The model documention however is a bit misleading especially 

https://github.com/unit8co/darts/blob/4a97140391f171e151c10ac6889eb9a9ce1ba70f/darts/models/forecasting/exponential_smoothing.py#L35

and 

https://github.com/unit8co/darts/blob/4a97140391f171e151c10ac6889eb9a9ce1ba70f/darts/models/forecasting/exponential_smoothing.py#L49-L51

If you want, you could adapt these lines instead for the PR? :)

2022-01-15 21:00 UTC, john-ramsey commented
- Clarified a bit by bringing in SeasonalityMode for the ETS seasonal component. Added the None option as well
- Formatted with Black

2022-01-21 08:02 UTC, dennisbader requested changes
Thanks a lot for that, looks good!
Just had a few minor suggestions, then it is ready to merge :)

2022-01-22 14:33 UTC, dennisbader commented on darts/models/forecasting/exponential_smoothing.py
> +
```suggestion
```

2022-01-22 14:40 UTC, dennisbader commented on darts/models/forecasting/exponential_smoothing.py
> +        """ Exponential Smoothing
for black
```suggestion
        """Exponential Smoothing
```

2022-01-22 14:41 UTC, dennisbader commented on darts/models/forecasting/exponential_smoothing.py
> +            Type of seasonal component. Either ``SeasonalityMode.ADDITIVE``, ``SeasonalityMode.MULTIPLICATIVE``, ``SeasonalityMode.NONE``, or ``None``.
for black
```suggestion
            Type of seasonal component. Either ``SeasonalityMode.ADDITIVE``, ``SeasonalityMode.MULTIPLICATIVE``, ``SeasonalityMode.NONE``, or ``None``.
```

2022-01-22 15:00 UTC, dennisbader commented on darts/models/forecasting/exponential_smoothing.py
> +        ``ExponentialSmoothing(trend=ModelMode.ADDITIVE, seasonal=SeasonalityMode.NONE)`` corresponds to a Holt's exponential smoothing.
```suggestion
        ``ExponentialSmoothing(trend=ModelMode.NONE, seasonal=SeasonalityMode.NONE)`` corresponds to a single
        exponential smoothing.
        ``ExponentialSmoothing(trend=ModelMode.ADDITIVE, seasonal=SeasonalityMode.NONE)`` corresponds to a Holt's
        exponential smoothing.
```

2022-01-22 15:00 UTC, dennisbader commented on darts/models/forecasting/exponential_smoothing.py
>              Defaults to ``ModelMode.ADDITIVE``.
```suggestion
            Type of trend component. Either ``ModelMode.ADDITIVE``, ``ModelMode.MULTIPLICATIVE``, ``ModelMode.NONE``,
            or ``None``. Defaults to ``ModelMode.ADDITIVE``.
```

2022-01-22 15:02 UTC, dennisbader commented on darts/models/forecasting/exponential_smoothing.py
> +            Defaults to ``SeasonalityMode.ADDITIVE``.
```suggestion
            Type of seasonal component. Either ``SeasonalityMode.ADDITIVE``, ``SeasonalityMode.MULTIPLICATIVE``,
            ``SeasonalityMode.NONE``, or ``None``. Defaults to ``SeasonalityMode.ADDITIVE``.
```

2022-01-22 18:35 UTC, john-ramsey commented
I have black auto-formatting in VS code and it caught none of this? 😬

Thanks

2022-01-22 19:18 UTC, dennisbader commented
Most of the issues like too long lines were detected by flask8 that we just integrated into CI.
However unit tests seem to behave strangely currently.  This seems to be an issue on our side

2022-01-24 19:12 UTC, dennisbader approved these changes
All tests passed now. Thanks again for contributing!

2022-01-24 19:12 UTC, merged